version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Australia/Sydney"
    commit-message:
      prefix: "[gem]"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Australia/Sydney"
    commit-message:
      prefix: "[docker]"
