default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  adapter: sqlite3
  database: db/<%= Rails.env %>.sqlite3

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
