---
default: &default
  competition_id: 111
  seasons:
    - 2020
    - 2021
  valid_event_types:
    - Error
    - Try
    - Goal
    - GoalMissed
    - FortyTwenty
    - KickBomb
    - Penalty
    - LineBreak
    - SinBin

development: 
  <<: *default

production:
  <<: *default