---
default: &default
  competition_id: 111
  seasons:
    - year: 2024
      last_regular_games_round: 25
  valid_event_types:
    - Error
    - Try
    - Goal
    - GoalMissed
    - FortyTwenty
    - KickBomb
    - Penalty
    - LineBreak
    - SinBin
    - OnePointFieldGoal
    - TwoPointFieldGoal
    - SetRestart
    - LineDropout
    - OnePointFieldGoalMissed
    - TwoPointFieldGoalMissed
    - RuckInfringement
    - OffsideWithinTenMetres
  valid_game_stat_types:
    - name: 'Possession %'
      id: 'possession_percentage'
    - name: 'Time In Possession'
      id: 'possession_time'
    - name: 'Completion Rate'
      id: 'completion_rate'
    - name: 'All Run Metres'
      id: 'run_metres'
    - name: 'Post Contact Metres'
      id: 'post_contact_metres'
    - name: 'Line Breaks'
      id: 'line_breaks'
    - name: 'Tackle Breaks'
      id: 'tackle_breaks'
    - name: 'Average Set Distance'
      id: 'avg_set_distance'
    - name: 'Kick Return Metres'
      id: 'kick_return_metres'
    - name: 'Offloads'
      id: 'offloads'
    - name: 'Total Passes'
      id: 'passes'
    - name: 'Dummy Passes'
      id: 'dummy_passes'
    - name: 'Kicks'
      id: 'kicks'
    - name: 'Kicking Metres'
      id: 'kicking_metres'
    - name: 'Forced Drop Outs'
      id: 'forced_drop_outs'
    - name: 'Bombs'
      id: 'bombs'
    - name: 'Effective Tackle %'
      id: 'effective_tackle_percentage'
    - name: 'Tackles Made'
      id: 'tackles_made'
    - name: 'Missed Tackles'
      id: 'missed_tackles'
    - name: 'Ineffective Tackles'
      id: 'ineffective_tackles'
    - name: 'Errors'
      id: 'erors'
    - name: 'Intercepts'
      id: 'intercepts'
    - name: 'Penalties Conceded'
      id: 'penalties_conceded'


development: 
  <<: *default

production:
  <<: *default
